# Generated by Django 4.2.6 on 2023-10-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_cv_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='DOB',
            field=models.DateField(default='2000-01-01', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college_id',
            field=models.CharField(default='Unknown College ID', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(default='Unknown Address', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_name',
            field=models.CharField(default='Unknown Address', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='Unknown Address', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='exame_result',
            field=models.FileField(default='Unknown Result', upload_to='exam_results/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='file_cv',
            field=models.FileField(default='Unknown CV', upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flexRadioDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='insta_username',
            field=models.CharField(default='Unknown Address', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='para',
            field=models.TextField(default='Uknown messages', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='Unknown Address', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(default='Unknown Photo', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(default='Unknown Address', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_username',
            field=models.CharField(default='Unknown Address', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_username',
            field=models.CharField(default='Unknown Address', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(default='Unknown Address', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Unknown Address', max_length=100),
        ),
    ]
