# Generated by Django 4.2.6 on 2023-10-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_userprofile_dob_userprofile_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_doc',
            field=models.FileField(default='Unknown DOC', upload_to='verified_doc/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college_id',
            field=models.FileField(default='Unknown College ID', upload_to='college_id/'),
        ),
    ]
