# Generated by Django 4.2.6 on 2023-10-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_textcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextContent',
        ),
    ]
