# Generated by Django 4.2.6 on 2023-10-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_delete_textcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Address', max_length=100)),
                ('course', models.CharField(default='Unknown Address', max_length=100)),
                ('college', models.CharField(default='Unknown Address', max_length=100)),
                ('responsibility', models.CharField(default='Unknown Address', max_length=100)),
                ('phone_number', models.CharField(default='Unknown Address', max_length=15)),
                ('email', models.EmailField(default='Unknown Address', max_length=200)),
                ('photo', models.ImageField(default='Unknown Address', upload_to='photos/')),
            ],
        ),
    ]
