# Generated by Django 4.2.6 on 2023-11-01 05:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0010_userlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userlogin',
            new_name='Dashboard',
        ),
    ]
