# Generated by Django 4.2.6 on 2023-11-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_dashboard_announcements_dashboard_calender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
