# Generated by Django 4.2.6 on 2023-11-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creator',
        ),
    ]
