# Generated by Django 4.2.6 on 2023-11-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='contact_information',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
