# Generated by Django 4.2.6 on 2023-11-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0022_adminprofile_id_card_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='id_card_generated',
        ),
        migrations.AddField(
            model_name='member',
            name='id_card_generated',
            field=models.BooleanField(default=False),
        ),
    ]
