# Generated by Django 4.2.6 on 2023-11-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_remove_adminprofile_id_card_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(choices=[('Advocate', 'Advocate'), ('Another in Law Field', 'Another in Law Field'), ('Law Student', 'Law Student'), ('Judge', 'Judge')], default='Advocate', max_length=30),
        ),
    ]
