# Generated by Django 4.2.6 on 2023-11-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0024_userprofile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(default='Unknown Address', max_length=100),
        ),
    ]
